### ISSUE TITLE
x-microcks-ref must be x-microcks-refs and ref should also be used to find unused params and requests

### ISSUE THREAD

**Issue by savvyintegrations** [microcks/microcks-spectral-ruleset#4]
### Describe the bug

Running 0.0.3 I ran into more bugs, specifically with `x-microcks-refs`.

### Expected behavior

Expected behavior is in this fixed script, which you can easily diff and then just apply as you see fit. These changes allowed me to run all the lint rules and fix them appropriately. 
[oas-verify-mocks.js.zip](https://github.com/microcks/microcks-spectral-ruleset/files/15358690/oas-verify-mocks.js.zip)

### Microcks version or git rev

0.0.3

**Comment by lbroudoux** [comment]
Thank you very much for opening and solving this!
